---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    name: in-cluster
  project: infra
  source:
    chart: istio/base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.16.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
