apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc.fullname" . }}-port
  labels:
    {{- include "grpc.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{.Values.service.containerPort}}
  selector:
    {{- include "grpc.selectorLabels" . | nindent 4 }}
