{{- if .Values.serviceMonitoring.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "grpc.name" . }}
  labels:
{{ include "grpc.labels" . | indent 4 }}
spec:
  endpoints:
    - interval: 10s
      port: http
      scheme: http
      path: /metrics
  jobLabel: {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grpc.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}