---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sig-local-static-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sig-local-static-provisioner
    name: in-cluster
  project: infra
  source:
    path: helm/provisioner
    repoUrl: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner
    targetRevision: 419972c214d8c5b139c83f2ba2580c3e9536d68f
    helm:
      values: |
        serviceMonitor:
          enabled: true
        classes:
          - name: local-storage
            hostDir: /mnt/k8s
            volumeMode: Filesystem
            storageClass: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
