---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nats
    name: in-cluster
  project: infra
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: 0.19.3
    helm:
      values: |
        cluster:
          enabled: true
          replicas: 10
        natsbox:
          enabled: true
        nats:
          jetstream:
            enabled: true
            fileStorage:
              enabled: true
              size: 1Gi
              volumeMode: Block
              storageClassName: local-storage-hdd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
