---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kiali-operator
    name: in-cluster
  project: infra
  source:
    chart: kiali-operator
    repoURL: https://kiali.org/helm-charts
    targetRevision: 1.30.0
    helm:
      values: |
        auth:
          strategy: anonymous
        cr:
          create: true
          namespace: istio-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
