---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: clickhouse
    name: in-cluster
  project: default
  source:
    chart: clickhouse
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.0.1
    helm:
      values: |
        global:
          storageClass: local-storage-nvme
        shards: 1
        replicaCount: 1
        ingress:
          enabled: true
          hostname: clickhouse.local
        persistence:
          enabled: true
        metrics:
          serviceMonitor:
            enabled: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
