---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: clickhouse
    name: in-cluster
  project: default
  source:
    path: "charts/apps/services/clickhouse"
    repoURL: https://github.com/ft-t/k8s
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
