apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: {{.Values.installationName}}
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      podTemplate: pod-template
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper
    clusters:
      - name: "default"
        layout:
          shardsCount: {{.Values.shardsCount}}
          replicasCount: {{.Values.replicaCount}}
    users:
      root/networks/ip: "::/0"
      root/password: EXRpjn9Sa6b95WGXhaR
      root/profile: default
  templates:
    podTemplates:
      - name: pod-template
        spec:
          nodeSelector:
            purpose: analytics
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: {{.Values.storageClassName}}
          resources:
            requests:
              storage: 5Gi