apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: {{.Values.installationName}}
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper.zoo1ns
    clusters:
      - name: "default"
        layout:
          shardsCount: {{.Values.shardsCount}}
          replicasCount: {{.Values.replicaCount}}
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: {{.Values.storageClassName}}
          resources:
            requests:
              storage: 5Gi