apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
spec:
  storageClassName: local-storage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: task-pv-claim
  hostPath:
    path: "/mnt/pvc/"
