{{/*{{- if .Values.persistence.enabled }}*/}}
{{/*kind: PersistentVolumeClaim*/}}
{{/*apiVersion: v1*/}}
{{/*metadata:*/}}
{{/*  name: {{ template "helm-guestbook.fullname" . }}*/}}
{{/*spec:*/}}
{{/*  storageClassName: {{ .Values.persistence.storageClass | quote }}*/}}
{{/*  accessModes:*/}}
{{/*    - {{ .Values.persistence.accessMode | quote }}*/}}
{{/*  resources:*/}}
{{/*    requests:*/}}
{{/*      storage: {{ .Values.persistence.size | quote }}*/}}
{{/*{{- end }}*/}}