service:
  type: ClusterIP
  port: 80
  containerPort: 50101

image:
  repository: skydev/testg
  pullPolicy: Always
  tag: "dev"

serviceMonitoring:
  enabled: true
  port: 50101

imagePullSecrets: []

namespace: default
replicaCount: 1

podAnnotations: {}
nodeSelector: { }
tolerations: [ ]
affinity: { }
podSecurityContext: {}
securityContext: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

itemsCount: 10

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 256Mi