service:
  type: ClusterIP
  port: 80
  containerPort: 8000

image:
  repository: skydev/vcs-stress
  pullPolicy: Always
  tag: "latest"

serviceMonitoring:
  enabled: false
  port: 8721

imagePullSecrets: []

namespace: default
replicaCount: 2

podAnnotations: {}
nodeSelector: { }
tolerations: [ ]
affinity: { }
podSecurityContext: {}
securityContext: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi