---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kiali-operator
    name: in-cluster
  project: default
  source:
    chart: kiali-operator
    repoURL: https://kiali.org/helm-charts
    targetRevision: 1.60.0
    helm:
      values: |
        cr:
          create: true
          namespace: istio-system
          spec:
            external_services:
              prometheus:
                url: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090"
              custom_dashboards:
                prometheus:
                  url: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090"
            auth:
              strategy: anonymous
            deployment:
              ingress:
                enabled: true
                hosts: ["kiali.qqw.ovh"]
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
