---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: redis
    name: in-cluster
  project: default
  source:
    path: "charts/apps/services/redis"
    repoURL: https://github.com/ft-t/k8s
    helm:
      releaseName: redis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true